### ISSUE TITLE
Request to implement a javascript

### ISSUE THREAD

**Issue by stephio** [Shoety/cordova-plugin-inappbrowserxwalk#1]
Great job, big help!

My feature request would be to have a close function which can be called from inside the page javascript to close the inappbrowser.
This would be specially helpful in case if the content has a e.g full screen video, and the user could close the page from within the video player layout.

Thanks!

**Comment by ClaasBrueggemann** [comment]
I have updated the plugin and added more features including the close function.

**Comment by stephio** [comment]
Thank you a lot!
