### ISSUE TITLE
Problem/Crash with HTML5 video fullscreen

### ISSUE THREAD

**Issue by goffioul** [Shoety/cordova-plugin-inappbrowserxwalk#16]
I've created a very simple application as follows:
- cordova 6.1.1
- crosswalk-cordova-webview-plugin: using crosswalk 18
- cordova-plugin-inappbrowserxwalk

The cordova app is the default template one, with just an additional button that trigger the following javascript:

`window.inAppBrowserXwalk.open('http://www.youtube.com', {});`

The in-app browser dialog is correctly displayed, I can navigate within youtube and play videos. The problem occur whenever I switch the video to fullscreen mode. Then in-app browser webview content disappear (I can see the cordova app), but the in-app browser toolbar with the Close button is still visible. The audio continues, but I don't get the video picture. If I press the Close button, the entire app crashes.

I've tried on 2 different platforms, ARMv7 and x86, with the same result.

Any hint or suggestion about this problem would be greatly appreciated. I would happily disable fullscreen support in the in-app browser, but it doesn't look like crosswalk has that capability.

**Comment by egdbear** [comment]
Any update on this?

**Comment by goffioul** [comment]
I've reported the problem to crosswalk, which is where the problem lies. There's a fix pending. See:
https://crosswalk-project.org/jira/browse/XWALK-6939
