### ISSUE TITLE
window.close doesn't work as expected

### ISSUE THREAD

**Issue by aaronfranco** [Shoety/cordova-plugin-inappbrowserxwalk#2]
Open a window from the app using then have a script that calls

```
window.close()
```

from the opened window. The plugin stops the entire app, not just the window that was opened. It should only close the opened window and return the user back to the app state that opened the window.

There are a few new features that need to be implemented for this to work properly. 
1. Return a reference to the browser window that was opened, similar to InAppBrowser
2. Enable the type of window to open "_blank," "_self," or "_system."

Ideally, this plugin will copy the functionality from the InAppBrowser making it a drop-in replacement :+1:

**Comment by ClaasBrueggemann** [comment]
I have updated the plugin and added more features including the close function.

**Comment by aaronfranco** [comment]
thanks for the update!
