### ISSUE TITLE
Implements .show() and hide() functions

### ISSUE THREAD

**Issue by marcusvbp** [Shoety/cordova-plugin-inappbrowserxwalk#3]
Hi friend.

You had made great work with this plugin.

I wish to make a suggestion: implement the functions .hide() and .show(). It will useful for showing a page only if it is full loaded.

Thank you e sorry the bad english.

**Comment by ClaasBrueggemann** [comment]
Hi Marcus,

i am going to implement that, maybe on the weekend ;)

**Comment by ClaasBrueggemann** [comment]
Done. Readme updated with new functions and options.
